// Drill bank (docs/content-pipeline.md §5): 60 questions, ~10 per category,
// each with a 3-step derivation and links into the numbers database.
// ids are stable — the Leitner scheduler keys on them; never reuse or rename.

export type DrillCategory = 'capacity' | 'latency' | 'story' | 'storage' | 'network' | 'cost'

export const DRILL_CATEGORIES: Record<DrillCategory, string> = {
  capacity: 'Single-machine capacity',
  latency: 'The latency ladder',
  story: 'Story → numbers',
  storage: 'Storage growth',
  network: 'Network',
  cost: 'Cost sanity',
}

export interface Drill {
  id: string
  cat: DrillCategory
  q: string
  unit: string
  ans: number
  /** log10 slider bounds */
  loExp: number
  hiExp: number
  derive: [string, string, string]
  /** ids into src/content/numbers.ts */
  numbersRefs: string[]
}

export const DRILLS: Drill[] = [
  /* ---------------- capacity ---------------- */
  {
    id: 'cap-app',
    cat: 'capacity',
    q: 'One modern app server (16 cores) serving a simple JSON API over HTTP. How many requests/second before it saturates?',
    unit: 'req/s',
    ans: 10000,
    loExp: 2,
    hiExp: 6,
    derive: [
      'A simple request costs ~1–2 ms of CPU (parse, validate, serialize).',
      'One core: 1000 ms ÷ 1.5 ms ≈ 700 req/s.',
      '16 cores × 700 ≈ 11k — call it 10k req/s per box.',
    ],
    numbersRefs: ['app-server-rps'],
  },
  {
    id: 'cap-pg-reads',
    cat: 'capacity',
    q: 'A single Postgres primary on good hardware, indexed point reads, working set cached in RAM. Reads per second?',
    unit: 'reads/s',
    ans: 30000,
    loExp: 2,
    hiExp: 6.5,
    derive: [
      'A cached point read is a few B-tree hops in RAM + protocol overhead ≈ 0.1–0.5 ms of work.',
      'Across cores with connection overhead: tens of thousands/s — 20–50k is the honest band.',
      "Uncached (touching disk) divides this by 10×: now you're paying SSD latency per read.",
    ],
    numbersRefs: ['pg-reads'],
  },
  {
    id: 'cap-pg-writes',
    cat: 'capacity',
    q: 'Same Postgres primary — durable WRITES per second (each must hit the write-ahead log)?',
    unit: 'writes/s',
    ans: 8000,
    loExp: 2,
    hiExp: 5.5,
    derive: [
      "Every commit must fsync the write-ahead log — you're bounded by sequential SSD flushes, not CPU.",
      'Group commit batches many transactions per flush, buying you thousands, not millions.',
      '5–10k TPS is the classic single-primary ceiling. Past it: shard, or buffer through a queue.',
    ],
    numbersRefs: ['pg-writes'],
  },
  {
    id: 'cap-redis',
    cat: 'capacity',
    q: 'One Redis node (single-threaded core doing the work). GET operations per second?',
    unit: 'ops/s',
    ans: 100000,
    loExp: 3,
    hiExp: 7,
    derive: [
      'A GET is a hash lookup in RAM: ~1 µs of actual work → in theory 1M/s per core.',
      'Network syscalls eat most of it; pipelining wins some back.',
      "~100k ops/s per node is the planning number — it's 10× a database because it skips the disk and the query engine entirely.",
    ],
    numbersRefs: ['redis-ops'],
  },
  {
    id: 'cap-kafka',
    cat: 'capacity',
    q: 'One Kafka broker on modern hardware. Messages per second (small ~1 KB messages)?',
    unit: 'msgs/s',
    ans: 1000000,
    loExp: 4,
    hiExp: 7.5,
    derive: [
      "Kafka's trick: it only appends sequentially — sequential I/O is ~1000× cheaper than random.",
      '1 KB × 1M/s = 1 GB/s, within reach of NVMe sequential bandwidth.',
      "~1M msgs/s per broker. It's fast because it refuses to do random I/O, not because of magic.",
    ],
    numbersRefs: ['kafka-msgs'],
  },
  {
    id: 'cap-nvme-iops',
    cat: 'capacity',
    q: 'One NVMe SSD, random 4 KB reads at full queue depth. IOPS?',
    unit: 'IOPS',
    ans: 750000,
    loExp: 3,
    hiExp: 7,
    derive: [
      'One flash read takes ~80 µs, so a single stream gets only ~12k/s.',
      'But the drive has many dies and deep queues — thousands of reads in flight at once.',
      'Parallelism × per-read physics ≈ 500k–1M random reads/s per drive.',
    ],
    numbersRefs: ['nvme-iops', 'nvme-read'],
  },
  {
    id: 'cap-hdd-iops',
    cat: 'capacity',
    q: 'One 7200 RPM spinning disk. Random reads per second?',
    unit: 'IOPS',
    ans: 120,
    loExp: 0,
    hiExp: 4,
    derive: [
      'Every random read waits ~4 ms of seek plus ~4 ms of rotation — moving metal.',
      '1000 ms ÷ 8 ms ≈ 120 operations per second, forever.',
      'B-trees, LSM-trees, WALs, and Kafka all exist to dodge this number.',
    ],
    numbersRefs: ['hdd-iops', 'hdd-seek'],
  },
  {
    id: 'cap-core-ops',
    cat: 'capacity',
    q: 'One CPU core doing simple in-memory operations (hash lookups on cached data). Operations per second?',
    unit: 'ops/s',
    ans: 50000000,
    loExp: 5,
    hiExp: 10,
    derive: [
      'A 3.3 GHz core retires ~3 billion simple instructions/s in a perfect world.',
      'A real "operation" (hash, compare, branch, pointer chase) is ~20–60 instructions with cache effects.',
      '3e9 ÷ 60 ≈ 50M ops/s per core — memory stalls, not arithmetic, set the ceiling.',
    ],
    numbersRefs: ['cpu-cycle', 'dram-access'],
  },
  {
    id: 'cap-compress',
    cat: 'capacity',
    q: 'Fast compression (snappy/lz4) throughput on one core?',
    unit: 'MB/s',
    ans: 500,
    loExp: 0.5,
    hiExp: 4,
    derive: [
      'Snappy-class compressors spend ~2 µs per KB.',
      '1 KB ÷ 2 µs = 500 MB/s per core, shrinking data 2–4×.',
      'That is why "compress before sending" is nearly always a win: CPU is cheaper than I/O.',
    ],
    numbersRefs: ['compress-1kb'],
  },
  {
    id: 'cap-nvme-seq',
    cat: 'capacity',
    q: 'One NVMe SSD, sequential write bandwidth?',
    unit: 'MB/s',
    ans: 3000,
    loExp: 1.5,
    hiExp: 4.5,
    derive: [
      'PCIe 4 x4 gives the drive ~8 GB/s of bus; flash program time is the real limit.',
      'Modern drives sustain 2–5 GB/s sequential writes (until the SLC cache runs out).',
      '~3 GB/s planning number — 25,000× the random throughput of a spinning disk.',
    ],
    numbersRefs: ['nvme-iops', 'kafka-msgs'],
  },

  /* ---------------- latency ladder ---------------- */
  {
    id: 'lat-l1',
    cat: 'latency',
    q: 'L1 cache hit. How long?',
    unit: 'ns',
    ans: 1,
    loExp: -0.5,
    hiExp: 2.5,
    derive: [
      'L1 is SRAM physically inside the core, millimetres from the ALU.',
      '≈ 4 cycles × 0.3 ns ≈ 1 ns.',
      'Fast because it is small and CLOSE — distance is the whole story.',
    ],
    numbersRefs: ['l1-hit'],
  },
  {
    id: 'lat-dram',
    cat: 'latency',
    q: 'Main memory (DRAM) random access. How long?',
    unit: 'ns',
    ans: 100,
    loExp: 0,
    hiExp: 4,
    derive: [
      'Select a row, bleed charge onto long wires, wait for sense amplifiers, rewrite the destroyed bit.',
      'The dance costs ~100 ns ≈ 300 CPU cycles of waiting.',
      '"Fits in cache" vs "lives in RAM" is a 100× cliff crossed billions of times per second.',
    ],
    numbersRefs: ['dram-access'],
  },
  {
    id: 'lat-nvme',
    cat: 'latency',
    q: 'NVMe SSD random read. How long?',
    unit: 'µs',
    ans: 80,
    loExp: 0,
    hiExp: 4,
    derive: [
      'Reading flash = sensing which of 8 charge levels each TLC cell holds — careful analog work.',
      '~50–100 µs per page read; call it 80 µs.',
      '800× slower than RAM, but it survives power-off. Databases live in this gap.',
    ],
    numbersRefs: ['nvme-read'],
  },
  {
    id: 'lat-hdd',
    cat: 'latency',
    q: 'Spinning disk (7200 RPM) random read. How long?',
    unit: 'ms',
    ans: 8,
    loExp: -1,
    hiExp: 2.5,
    derive: [
      'Half a rotation on average (4.2 ms at 7200 RPM) plus ~4 ms of head seek.',
      '≈ 8 ms of physical motion per random read.',
      'This number cannot improve — it is bounded by the platter tearing itself apart.',
    ],
    numbersRefs: ['hdd-seek'],
  },
  {
    id: 'lat-dc-rtt',
    cat: 'latency',
    q: 'Round trip between two servers in the same datacenter?',
    unit: 'µs',
    ans: 500,
    loExp: 1,
    hiExp: 4,
    derive: [
      'Light across the building: ~0.5 µs — irrelevant.',
      'Serialization, switch hops, and two kernel network stacks: ~499.5 µs.',
      '~0.5 ms per hop: inside a DC the floor is software, not physics.',
    ],
    numbersRefs: ['same-dc-rtt'],
  },
  {
    id: 'lat-xregion',
    cat: 'latency',
    q: 'Round trip between US East and US West?',
    unit: 'ms',
    ans: 70,
    loExp: 0,
    hiExp: 3.5,
    derive: [
      '~4,700 km of fiber at 200,000 km/s (glass slows light 1.47×) → ~24 ms one way.',
      '~48 ms round trip as the physical floor.',
      'Real routing brings it to 60–80 ms. Trust it forever: it is the speed of light.',
    ],
    numbersRefs: ['cross-region-rtt'],
  },
  {
    id: 'lat-miss-chain',
    cat: 'latency',
    q: 'A read misses the in-memory cache and falls through to an NVMe-backed database. Total latency ≈ ?',
    unit: 'µs',
    ans: 85,
    loExp: 0,
    hiExp: 4,
    derive: [
      'The cache lookup that missed: ~1 µs. Irrelevant.',
      'The SSD page read behind the database: ~80 µs, plus a few µs of software.',
      'Chains are dominated by their slowest hop — add the big number, ignore the rest.',
    ],
    numbersRefs: ['nvme-read', 'redis-ops'],
  },
  {
    id: 'lat-hops',
    cat: 'latency',
    q: 'A request fans through 6 sequential microservice hops inside one DC before answering. Latency floor from hops alone?',
    unit: 'ms',
    ans: 3,
    loExp: -1,
    hiExp: 2,
    derive: [
      'Each in-DC hop costs ~0.5 ms of round trip.',
      '6 × 0.5 ms = 3 ms spent before any real work happens.',
      'Chatty microservices pay this toll on every request — it is why service meshes obsess over hop counts.',
    ],
    numbersRefs: ['same-dc-rtt'],
  },
  {
    id: 'lat-compress',
    cat: 'latency',
    q: 'Compressing 1 KB with a fast compressor (snappy). How long?',
    unit: 'µs',
    ans: 2,
    loExp: -1,
    hiExp: 3,
    derive: [
      '~6,000 CPU cycles of pure arithmetic.',
      '≈ 2 µs on one core.',
      'Sending that KB cross-region costs 70 ms — compression pays for itself 1000:1.',
    ],
    numbersRefs: ['compress-1kb'],
  },
  {
    id: 'lat-consensus',
    cat: 'latency',
    q: 'A strongly-consistent write across US East + West replicas (consensus, 2 round trips). Latency?',
    unit: 'ms',
    ans: 150,
    loExp: 0.5,
    hiExp: 3.5,
    derive: [
      'Consensus happy path: propose→acks, commit→acks = 2 round trips to a majority.',
      '2 × 70 ms cross-region RTT ≈ 140 ms, plus fsync and software.',
      '~150 ms per global strong write — geography, invoiced. This is why global systems avoid synchronous consensus per write.',
    ],
    numbersRefs: ['cross-region-rtt'],
  },

  /* ---------------- story → numbers ---------------- */
  {
    id: 'story-dau-avg',
    cat: 'story',
    q: '10M daily active users, each making 50 requests/day. AVERAGE requests per second?',
    unit: 'req/s',
    ans: 5800,
    loExp: 2,
    hiExp: 6,
    derive: [
      '10M × 50 = 500M requests/day.',
      '÷ 86,400 s ≈ 5,800 req/s.',
      'Shortcut: 1M/day ≈ 12/s — memorize the shortcut, not the answer.',
    ],
    numbersRefs: ['req-per-day-rule'],
  },
  {
    id: 'story-dau-peak',
    cat: 'story',
    q: 'Same app: 5,800 req/s average, consumer traffic. What PEAK should you design for?',
    unit: 'req/s',
    ans: 17000,
    loExp: 3,
    hiExp: 5.5,
    derive: [
      'Human traffic is diurnal: evenings concentrate ~half the day into a few hours.',
      'Peak = 2–5× average for consumer apps; 3× is the planning default.',
      '5,800 × 3 ≈ 17k req/s. Quote both numbers out loud in interviews.',
    ],
    numbersRefs: ['peak-multiplier', 'req-per-day-rule'],
  },
  {
    id: 'story-iot',
    cat: 'story',
    q: '60,000 IoT trackers, each reporting every 8 seconds. Writes per second?',
    unit: 'writes/s',
    ans: 7500,
    loExp: 2,
    hiExp: 5.5,
    derive: [
      'Machines phone home on a timer: rate = devices ÷ interval.',
      '60,000 ÷ 8 s = 7,500/s — flat, 24/7, no evening peak.',
      'The danger is synchronized bursts (reconnect herds), not daily cycles.',
    ],
    numbersRefs: ['req-per-day-rule', 'peak-multiplier'],
  },
  {
    id: 'story-1m-day',
    cat: 'story',
    q: 'A service handles 1 million requests per day. Average requests per second?',
    unit: 'req/s',
    ans: 12,
    loExp: -1,
    hiExp: 3,
    derive: [
      'One day is 86,400 seconds — call it 100k for mental math.',
      '1M ÷ 86,400 ≈ 11.6.',
      'The most useful constant in capacity math: 1M/day ≈ 12/s. Everything scales linearly from it.',
    ],
    numbersRefs: ['req-per-day-rule'],
  },
  {
    id: 'story-chat',
    cat: 'story',
    q: '2M DAU chat app, each sending 40 messages/day. Average messages per second?',
    unit: 'msgs/s',
    ans: 900,
    loExp: 1,
    hiExp: 5,
    derive: [
      '2M × 40 = 80M messages/day.',
      '80 × 12 (the 1M/day ≈ 12/s rule) ≈ 950/s.',
      "Each message also fans out to recipients' devices and inboxes — the write is never alone.",
    ],
    numbersRefs: ['req-per-day-rule'],
  },
  {
    id: 'story-onsale',
    cat: 'story',
    q: 'Stadium on-sale: 500k fans on the page, each refreshing ~5 times per minute. Requests per second?',
    unit: 'req/s',
    ans: 42000,
    loExp: 3,
    hiExp: 6,
    derive: [
      '500,000 × 5 = 2.5M refreshes/minute.',
      '÷ 60 ≈ 42k req/s, sustained for the whole rush.',
      'No diurnal curve saves you here — everyone is synchronized by the clock on purpose.',
    ],
    numbersRefs: ['req-per-day-rule', 'peak-multiplier'],
  },
  {
    id: 'story-video-upload',
    cat: 'story',
    q: '10M DAU; 1% upload one 5 MB video daily. AVERAGE upload bandwidth?',
    unit: 'MB/s',
    ans: 6,
    loExp: -1,
    hiExp: 3,
    derive: [
      '100k uploads/day × 5 MB = 500 GB/day of ingress.',
      '500 GB ÷ 86,400 s ≈ 5.8 MB/s average.',
      'Tiny! Upload bandwidth is rarely the problem — transcoding CPU and storage growth are.',
    ],
    numbersRefs: ['req-per-day-rule', 'storage-cost'],
  },
  {
    id: 'story-blackfriday',
    cat: 'story',
    q: 'Checkout runs 5k orders/s on a normal day. What should Black Friday capacity planning assume?',
    unit: 'orders/s',
    ans: 20000,
    loExp: 3,
    hiExp: 5.5,
    derive: [
      'Event peaks are sharper than diurnal peaks: 3–5× normal is the observed band.',
      '5k × 4 ≈ 20k orders/s for the spike window.',
      'And orders are WRITES — caches will not save you; this number sizes the primary/queue.',
    ],
    numbersRefs: ['peak-multiplier', 'pg-writes'],
  },
  {
    id: 'story-fanout',
    cat: 'story',
    q: 'Feed: 1,000 posts/s, average author has 200 followers, fan-out-on-write. Timeline writes per second?',
    unit: 'writes/s',
    ans: 200000,
    loExp: 3,
    hiExp: 7,
    derive: [
      'Every post becomes one write PER FOLLOWER: 1,000 × 200 = 200k/s.',
      'That is 25 Postgres primaries of write load — from 1k posts.',
      'Fan-out multiplies invisibly; the celebrity with 50M followers breaks the average entirely (hybrid fan-out exists for exactly her).',
    ],
    numbersRefs: ['pg-writes', 'partition-write-cap'],
  },
  {
    id: 'story-gps',
    cat: 'story',
    q: '1M rideshare drivers, GPS ping every 4 seconds. Location writes per second?',
    unit: 'writes/s',
    ans: 250000,
    loExp: 3,
    hiExp: 7,
    derive: [
      '1,000,000 ÷ 4 s = 250k writes/s, around the clock.',
      '25× a single primary — this workload is born sharded.',
      'And it is why location systems use in-memory stores with TTLs: the data expires faster than disks care.',
    ],
    numbersRefs: ['partition-write-cap', 'redis-ops'],
  },

  /* ---------------- storage growth ---------------- */
  {
    id: 'stor-events-day',
    cat: 'storage',
    q: '10M DAU, each writing 5 events of 1 KB per day. Storage accumulated per day?',
    unit: 'bytes/day',
    ans: 5e10,
    loExp: 8,
    hiExp: 13,
    derive: [
      '10M × 5 × 1 KB = 50M KB = 50 GB/day.',
      'Shape: users × actions × size. Decompose out loud; nobody cares about exact digits.',
      '≈ 18 TB/year — a handful of drives. Access patterns, not volume, are the usual problem.',
    ],
    numbersRefs: ['req-per-day-rule', 'storage-cost'],
  },
  {
    id: 'stor-events-year',
    cat: 'storage',
    q: 'Same 50 GB/day of events. Storage after one year?',
    unit: 'bytes',
    ans: 1.8e13,
    loExp: 11,
    hiExp: 15,
    derive: [
      '50 GB × 365 ≈ 18 TB.',
      'Always quote growth WITH retention: "18 TB/year, so 90 TB at 5-year retention".',
      'Then say the magic word: tiering. Hot 30 days on SSD, the rest in object storage.',
    ],
    numbersRefs: ['storage-cost'],
  },
  {
    id: 'stor-tweets',
    cat: 'storage',
    q: 'Twitter-scale text: 500M tweets/day at ~300 bytes each. Storage per day (text only)?',
    unit: 'bytes/day',
    ans: 1.5e11,
    loExp: 9,
    hiExp: 13,
    derive: [
      '500M × 300 B = 150 GB/day.',
      'A decade of all tweets is ~½ PB — text is basically free.',
      'The real storage is media: one photo ≈ 10,000 tweets. Always split text from blobs.',
    ],
    numbersRefs: ['storage-cost'],
  },
  {
    id: 'stor-video-hour',
    cat: 'storage',
    q: 'One hour of 1080p video at streaming bitrate (~5 Mbps). File size?',
    unit: 'bytes',
    ans: 2.2e9,
    loExp: 7,
    hiExp: 11,
    derive: [
      '5 Mbps ≈ 0.625 MB/s.',
      '× 3,600 s ≈ 2.2 GB/hour.',
      'Bitrate × time beats resolution math every time — memorize 5 Mbps for 1080p, ~4× per resolution step.',
    ],
    numbersRefs: ['storage-cost', 'egress-cost'],
  },
  {
    id: 'stor-cameras',
    cat: 'storage',
    q: '10,000 security cameras recording 1080p continuously. Storage per day?',
    unit: 'bytes/day',
    ans: 5.4e14,
    loExp: 12,
    hiExp: 16,
    derive: [
      'One camera: 2.2 GB/hour × 24 ≈ 54 GB/day.',
      '× 10,000 cameras ≈ 540 TB/day. Half a petabyte. Daily.',
      'This is why surveillance systems transcode down, keep motion-only, and expire aggressively.',
    ],
    numbersRefs: ['storage-cost'],
  },
  {
    id: 'stor-rows',
    cat: 'storage',
    q: 'A Postgres table with 1 billion rows of ~100 bytes of payload each. Table size on disk?',
    unit: 'bytes',
    ans: 1.5e11,
    loExp: 9,
    hiExp: 13,
    derive: [
      'Payload: 1e9 × 100 B = 100 GB.',
      'Row headers, page overhead, and bloat add ~40–50%.',
      '≈ 150 GB before indexes — and each index re-stores its columns again.',
    ],
    numbersRefs: ['storage-cost', 'pg-reads'],
  },
  {
    id: 'stor-backups',
    cat: 'storage',
    q: 'Nightly full backup of a 500 GB database, 30-day retention. Total backup storage?',
    unit: 'bytes',
    ans: 1.5e13,
    loExp: 11,
    hiExp: 15,
    derive: [
      '500 GB × 30 = 15 TB of mostly-identical copies.',
      'At $0.02/GB/mo that is ~$300/mo to store redundancy of redundancy.',
      'Incremental + periodic full is the standard answer; say it before the interviewer asks.',
    ],
    numbersRefs: ['storage-cost'],
  },
  {
    id: 'stor-logs',
    cat: 'storage',
    q: '10k req/s through 3 services, each logging one 200-byte line per request. Log volume per day?',
    unit: 'bytes/day',
    ans: 5e11,
    loExp: 9,
    hiExp: 14,
    derive: [
      '10k × 3 × 200 B = 6 MB/s of logs.',
      '× 86,400 ≈ 520 GB/day — the logs outweigh the data they describe.',
      'Hence sampling, structured logs, and short hot retention. Observability is a storage workload.',
    ],
    numbersRefs: ['req-per-day-rule', 'storage-cost'],
  },
  {
    id: 'stor-profiles',
    cat: 'storage',
    q: '100M user profiles at ~2 KB each. Total size?',
    unit: 'bytes',
    ans: 2e11,
    loExp: 9,
    hiExp: 13,
    derive: [
      '100M × 2 KB = 200 GB.',
      'That FITS IN RAM on one big box (or 2–3 cache nodes).',
      'The instinct this builds: "all users" is often small; "all events" is what grows without bound.',
    ],
    numbersRefs: ['dram-access', 'redis-ops'],
  },
  {
    id: 'stor-chat-5y',
    cat: 'storage',
    q: 'Chat app: 2M DAU × 40 messages/day × ~100 bytes, kept 5 years. Total?',
    unit: 'bytes',
    ans: 1.5e13,
    loExp: 11,
    hiExp: 15,
    derive: [
      '80M msgs/day × 100 B = 8 GB/day.',
      '× 365 × 5 ≈ 15 TB.',
      'Retention is a product decision wearing an engineering costume — always ask for it.',
    ],
    numbersRefs: ['storage-cost', 'req-per-day-rule'],
  },

  /* ---------------- network ---------------- */
  {
    id: 'net-light-ns',
    cat: 'network',
    q: 'How far does light travel in one nanosecond?',
    unit: 'm',
    ans: 0.3,
    loExp: -2,
    hiExp: 2,
    derive: [
      '299,792 km/s × 1e-9 s ≈ 30 cm.',
      "Grace Hopper's wire: a nanosecond you can hold.",
      'Every latency number in this game is this constant, multiplied.',
    ],
    numbersRefs: ['cpu-cycle'],
  },
  {
    id: 'net-bdp',
    cat: 'network',
    q: 'To fill a 1 Gbps link at 70 ms RTT, how many bytes must one TCP stream keep in flight?',
    unit: 'bytes',
    ans: 8.75e6,
    loExp: 4,
    hiExp: 9,
    derive: [
      'Throughput = window ÷ RTT, so window = bandwidth × RTT.',
      '125 MB/s × 0.07 s ≈ 8.75 MB.',
      'Default windows are far smaller — which is why single streams underuse fat links.',
    ],
    numbersRefs: ['bdp'],
  },
  {
    id: 'net-stream',
    cat: 'network',
    q: 'One TCP stream, 256 KB window, 70 ms RTT. Max throughput?',
    unit: 'MB/s',
    ans: 3.7,
    loExp: -1,
    hiExp: 3,
    derive: [
      'The sender stalls every window waiting a full RTT for ACKs.',
      '256 KB ÷ 0.07 s ≈ 3.7 MB/s — on a link carrying 125 MB/s.',
      '3% utilization, and the network gets blamed. Window, not bandwidth, was the bottleneck.',
    ],
    numbersRefs: ['bdp', 'cross-region-rtt'],
  },
  {
    id: 'net-tls',
    cat: 'network',
    q: 'TCP + TLS handshakes before the first byte, for a user 100 ms away?',
    unit: 'ms',
    ans: 200,
    loExp: 0.5,
    hiExp: 3.5,
    derive: [
      'TCP: 1 round trip. TLS 1.3: 1 more (older TLS: 2).',
      '2 × 100 ms = 200 ms of pure ceremony before your server sees the request.',
      'This is why edges terminate TLS near users and why connection reuse matters more than server speed.',
    ],
    numbersRefs: ['cross-region-rtt'],
  },
  {
    id: 'net-page',
    cat: 'network',
    q: 'How many HTTP requests does an average web page load make?',
    unit: 'requests',
    ans: 70,
    loExp: 0,
    hiExp: 3,
    derive: [
      'HTML, then CSS, JS bundles, fonts, images, API calls, analytics…',
      'HTTP Archive median: ~70 requests, ~2 MB.',
      '"10k page views/s" is ~700k req/s somewhere — decide early what the CDN absorbs.',
    ],
    numbersRefs: ['page-requests'],
  },
  {
    id: 'net-geo',
    cat: 'network',
    q: 'Round trip over a geostationary satellite link?',
    unit: 'ms',
    ans: 500,
    loExp: 1,
    hiExp: 3.5,
    derive: [
      'GEO orbit: 36,000 km up — four legs for a round trip ≈ 144,000 km.',
      '÷ 300,000 km/s ≈ 480 ms, plus ground processing.',
      'Physics again: it is why Starlink flies 60× lower, and why GEO internet felt unusable for calls.',
    ],
    numbersRefs: ['cross-region-rtt'],
  },
  {
    id: 'net-az',
    cat: 'network',
    q: 'Round trip between two availability zones in the same region?',
    unit: 'ms',
    ans: 1.5,
    loExp: -1.5,
    hiExp: 2,
    derive: [
      'AZs are separate campuses kilometres apart: ~1–2 ms round trip.',
      '3–4× an in-DC hop, ~50× less than cross-region.',
      'Cheap enough for synchronous replication — exactly why multi-AZ is the default durability story.',
    ],
    numbersRefs: ['same-dc-rtt', 'cross-region-rtt'],
  },
  {
    id: 'net-download',
    cat: 'network',
    q: 'Downloading a 1 GB file over a 100 Mbps connection. How long?',
    unit: 's',
    ans: 80,
    loExp: 0,
    hiExp: 3.5,
    derive: [
      '100 Mbps = 12.5 MB/s.',
      '1,000 MB ÷ 12.5 ≈ 80 seconds.',
      'Bits vs bytes is the classic 8× error — say the units out loud.',
    ],
    numbersRefs: ['bdp'],
  },
  {
    id: 'net-dc-hop',
    cat: 'network',
    q: 'One service-to-service call inside a datacenter (request + reply). Time cost?',
    unit: 'µs',
    ans: 500,
    loExp: 1,
    hiExp: 4,
    derive: [
      'Propagation is sub-microsecond; kernels, serialization, and switches are the cost.',
      '≈ 500 µs round trip ≈ 1.5 million CPU cycles of somebody waiting.',
      'The unit of microservice guilt: every extra hop is half a millisecond nobody gets back.',
    ],
    numbersRefs: ['same-dc-rtt'],
  },
  {
    id: 'net-region-out',
    cat: 'network',
    q: 'A strongly-consistent read served from the region NEXT DOOR (one round trip away). Added latency vs local?',
    unit: 'ms',
    ans: 70,
    loExp: 0,
    hiExp: 3,
    derive: [
      'One cross-region round trip: ~70 ms.',
      'Local read: ~1 ms. The remote hop is 70× the entire local operation.',
      'This asymmetry is the whole case for replicating data NEAR readers and accepting staleness.',
    ],
    numbersRefs: ['cross-region-rtt', 'same-dc-rtt'],
  },

  /* ---------------- cost sanity ---------------- */
  {
    id: 'cost-box',
    cat: 'cost',
    q: 'A committed 16-core cloud VM (your standard app server). Monthly cost?',
    unit: '$/mo',
    ans: 150,
    loExp: 0.5,
    hiExp: 4,
    derive: [
      'On-demand lists ~$580/mo for 16 vCPUs.',
      'Reserved/spot pricing cuts 60–75%.',
      '~$150/mo committed — the unit price of the compute tier.',
    ],
    numbersRefs: ['server-cost'],
  },
  {
    id: 'cost-1k',
    cat: 'cost',
    q: 'How many app servers (10k req/s each) does $1,000/mo buy?',
    unit: 'servers',
    ans: 6,
    loExp: 0,
    hiExp: 2,
    derive: [
      '$1,000 ÷ $150 ≈ 6.6 boxes.',
      'That is ~60k req/s of app tier for the price of a phone bill.',
      'Compute is cheap; the database and the people are not. Spend accordingly.',
    ],
    numbersRefs: ['server-cost', 'app-server-rps'],
  },
  {
    id: 'cost-100tb-store',
    cat: 'cost',
    q: 'Storing 100 TB in object storage. Monthly cost?',
    unit: '$/mo',
    ans: 2000,
    loExp: 1,
    hiExp: 5,
    derive: [
      '100,000 GB × $0.02/GB/mo.',
      '≈ $2,000/mo — a fraction of one engineer.',
      'Storage is rarely the line item that matters. Watch what the data DOES, not what it weighs.',
    ],
    numbersRefs: ['storage-cost'],
  },
  {
    id: 'cost-100tb-egress',
    cat: 'cost',
    q: 'Serving that same 100 TB OUT to the internet, once. Cost?',
    unit: '$',
    ans: 9000,
    loExp: 1.5,
    hiExp: 5.5,
    derive: [
      '100,000 GB × ~$0.09/GB egress.',
      "≈ $9,000 — 4.5× the monthly cost of storing it.",
      "Egress is the cloud's quiet moat; it is why video companies negotiate CDN contracts before hiring.",
    ],
    numbersRefs: ['egress-cost'],
  },
  {
    id: 'cost-cdn-gb',
    cat: 'cost',
    q: 'CDN delivery price per GB (at reasonable volume)?',
    unit: '$/GB',
    ans: 0.03,
    loExp: -3.5,
    hiExp: 0.5,
    derive: [
      'CDN list prices: $0.02–0.08/GB, falling fast with commitment.',
      'Cheaper than cloud egress and closer to users — a rare double win.',
      'This is why "put a CDN in front" is almost always move one.',
    ],
    numbersRefs: ['egress-cost'],
  },
  {
    id: 'cost-engineer',
    cat: 'cost',
    q: 'One senior engineer, fully loaded (salary + benefits + overhead). Monthly cost to the company?',
    unit: '$/mo',
    ans: 25000,
    loExp: 3,
    hiExp: 5.5,
    derive: [
      '$200–300k/year loaded is normal for senior in a major market.',
      '≈ $25k/mo — 160 app servers walking around in shoes.',
      'The strongest cost argument in any design review: does this save more engineer-hours than it costs?',
    ],
    numbersRefs: ['server-cost'],
  },
  {
    id: 'cost-events-s3',
    cat: 'cost',
    q: 'Archiving 18 TB/year of event data in object storage. Monthly cost by year-end?',
    unit: '$/mo',
    ans: 360,
    loExp: 0.5,
    hiExp: 4,
    derive: [
      '18,000 GB × $0.02/GB/mo ≈ $360/mo.',
      'Growing linearly: year 5 is ~$1,800/mo — still under a tenth of an engineer.',
      '"Keep everything forever" is often rational; know the number before assuming otherwise.',
    ],
    numbersRefs: ['storage-cost'],
  },
  {
    id: 'cost-replicas',
    cat: 'cost',
    q: 'Serving 200k reads/s from read replicas (20k reads/s, $400 each). Monthly cost?',
    unit: '$/mo',
    ans: 4000,
    loExp: 2,
    hiExp: 5.5,
    derive: [
      '200k ÷ 20k = 10 replicas.',
      '10 × $400 = $4,000/mo.',
      'Compare: two $200 cache nodes at 85% hit absorb 170k of those reads for $400. Caches are ~8× cheaper per absorbed read.',
    ],
    numbersRefs: ['server-cost', 'redis-ops'],
  },
  {
    id: 'cost-cache-absorb',
    cat: 'cost',
    q: 'A $200/mo cache node at 85% hit rate on 100k lookups/s absorbs how many reads/s per monthly dollar?',
    unit: 'reads/s per $',
    ans: 425,
    loExp: 0,
    hiExp: 4,
    derive: [
      'It absorbs 85,000 reads/s for $200/mo.',
      '85,000 ÷ 200 ≈ 425 reads/s per monthly dollar.',
      'A replica: 20,000 ÷ 400 = 50. The cache is ~8× cheaper per read — WHEN the hit rate holds.',
    ],
    numbersRefs: ['redis-ops', 'server-cost'],
  },
  {
    id: 'cost-ticketsale',
    cat: 'cost',
    q: 'Infra to survive a 45k req/s ticket on-sale (app tier + cache + DB + replicas). Monthly cost, roughly?',
    unit: '$/mo',
    ans: 2500,
    loExp: 2,
    hiExp: 5,
    derive: [
      '5 app ($750) + 2 cache ($400) + primary ($600) + 2 replicas ($800).',
      '≈ $2,550/mo for a stack that survives a stadium rush.',
      'The lesson: architecture, not spend, is what passes. 10× the money on the wrong shape still falls over.',
    ],
    numbersRefs: ['server-cost', 'app-server-rps'],
  },
]
