// The numbers database (docs/architecture.md · "Numbers database").
// Every number the game displays must be derivable from an entry here.
// derivation is exactly 3 steps: mechanism → math → result.

export interface NumberEntry {
  id: string
  value: number
  unit: string
  derivation: [string, string, string]
  boundingPhysics: string
  /** which Lab toy makes this number unforgettable (null = no toy yet) */
  toyId: string | null
  confusions: string
  simplifies?: string
}

export const NUMBERS: NumberEntry[] = [
  /* ---------- the latency ladder ---------- */
  {
    id: 'cpu-cycle',
    value: 0.3,
    unit: 'ns',
    derivation: [
      'A 3.3 GHz clock ticks 3.3 billion times per second.',
      '1 ÷ 3.3e9 seconds ≈ 0.3 ns per tick.',
      'In 0.3 ns light travels only 9 cm — a signal cannot cross a bigger chip in one tick, which is why dies are ~2 cm and clocks stalled near 3–5 GHz.',
    ],
    boundingPhysics: 'Speed of light across the die; heat (power ∝ V²·f) capped the frequency race in ~2005.',
    toyId: 'light',
    confusions: 'A cycle is not an instruction — modern cores retire several instructions per cycle, and stall for hundreds waiting on memory.',
  },
  {
    id: 'l1-hit',
    value: 1,
    unit: 'ns',
    derivation: [
      'L1 is ~48 KB of SRAM physically inside the core — 6 transistors per bit, no capacitor to recharge.',
      'Access ≈ 4 cycles × 0.3 ns ≈ 1 ns.',
      'It is fast because it is SMALL and CLOSE: the round trip is a few millimetres of wire.',
    ],
    boundingPhysics: 'Wire length: bigger memories need longer wires and more address-decode logic, so big and fast are geometrically incompatible.',
    toyId: 'light',
    confusions: 'L1 is per-core, not shared; hitting in a neighbor core’s cache costs far more (coherence traffic).',
  },
  {
    id: 'l2-hit',
    value: 4,
    unit: 'ns',
    derivation: [
      '~1 MB per core, still SRAM, a few mm farther from the ALU.',
      '≈ 14 cycles × 0.3 ns ≈ 4 ns.',
      'Each hierarchy level is ~4–10× bigger and ~4–10× slower — the ratio repeats all the way down to cross-region.',
    ],
    boundingPhysics: 'Same wire-length geometry as L1, one ring farther out.',
    toyId: null,
    confusions: 'A 4–10× latency ratio between adjacent layers of ANY system is a healthy hierarchy, not a bug.',
  },
  {
    id: 'l3-hit',
    value: 12,
    unit: 'ns',
    derivation: [
      'L3 is tens of MB of SRAM shared by all cores, physically spread across the die.',
      '≈ 40 cycles × 0.3 ns ≈ 12 ns.',
      'Shared means farther: the data may sit in a slice on the other side of the chip.',
    ],
    boundingPhysics: 'On-die distance plus arbitration between cores.',
    toyId: null,
    confusions: 'L3 is the last stop before the ~10× cliff to DRAM — "fits in L3" vs "spills to RAM" decides many benchmark mysteries.',
  },
  {
    id: 'dram-access',
    value: 100,
    unit: 'ns',
    derivation: [
      'DRAM stores each bit as charge on a microscopic capacitor (1 transistor + 1 capacitor — that is why it is dense and cheap).',
      'Reading = select a row, let a whisper of charge bleed onto a long wire, wait for a sense amplifier to decide 0-or-1, then REWRITE the bit the read destroyed.',
      'The whole dance ≈ 100 ns ≈ 300 CPU cycles of the core doing nothing.',
    ],
    boundingPhysics: 'Sense-amplifier settling time on long, high-capacitance wires; capacitors leak, so every row is refreshed every 64 ms forever.',
    toyId: 'dram',
    confusions: 'Sequential/streaming DRAM reads amortize to much better than 100 ns — the number is for a RANDOM access.',
    simplifies: 'Row-buffer hits, prefetching, and NUMA distance all move this number in real machines.',
  },
  {
    id: 'cache-line',
    value: 64,
    unit: 'bytes',
    derivation: [
      'The CPU never fetches a lone byte — it moves memory in fixed 64-byte blocks called cache lines (essentially every modern chip).',
      'Touch one byte and its 63 neighbours ride along for free; with 8-byte numbers, one miss pre-pays the next 7 accesses.',
      'So a sequential walk misses ~1 in 8, while a random walk drags in a fresh 64-byte line to use ~8 bytes of it — wasting 7/8 of the memory bandwidth it paid for.',
    ],
    boundingPhysics: 'DRAM is fastest in bursts — open a row, stream the whole line — so moving 64 B costs almost the same as 1 B. The line is free spatial locality, if you use it.',
    toyId: 'cachecliff',
    confusions: 'A cache line (64 B, the hardware transfer unit) is not a page (4 KB, the virtual-memory mapping unit) — different mechanisms, often confused.',
  },
  {
    id: 'page-size',
    value: 4,
    unit: 'KB (virtual-memory page)',
    derivation: [
      'The OS hands out memory in fixed pages, not bytes — 4 KB on essentially every system, each with one page-table entry mapping virtual → physical.',
      'Smaller pages waste less on partial fills but need more table entries and TLB slots; 4 KB is the decades-old compromise.',
      'A TLB of ~1500 entries therefore covers only ~6 MB (1500 × 4 KB) before translations start missing — a ceiling independent of how much RAM you have.',
    ],
    boundingPhysics: 'A fragmentation-vs-bookkeeping tradeoff: bigger pages waste more memory per allocation, smaller pages cost more page-table and TLB pressure.',
    toyId: 'tlb-toll',
    confusions: 'A page (4 KB, the OS mapping unit) is not a cache line (64 B, the hardware transfer unit). Huge pages (2 MB/1 GB) exist precisely to stretch TLB reach for big workloads.',
  },
  {
    id: 'clock-ceiling',
    value: 4,
    unit: 'GHz (air-cooled ceiling)',
    derivation: [
      'A transistor burns energy each time it switches, and a higher clock needs a higher voltage to switch cleanly — so dynamic power scales like frequency cubed (P ∝ V²·f, with V rising with f).',
      'A mainstream package sheds roughly 100 W of heat; setting f³-power equal to that budget lands the ceiling near 4 GHz.',
      'Double the clock ⇒ ~8× the heat, so stock clocks have sat at ~3–5 GHz for two decades while core COUNTS grew instead.',
    ],
    boundingPhysics: 'Heat: dynamic power ∝ f³ against a fixed cooling budget — the end of Dennard scaling (~2005), the reason CPUs went multi-core.',
    toyId: 'heat-wall',
    confusions: 'Turbo/boost briefly beats the steady ceiling by borrowing thermal headroom — it is not a higher sustainable clock. GPUs dodge the wall with many slow cores, not one fast one.',
  },
  {
    id: 'mispredict-penalty',
    value: 15,
    unit: 'cycles (~5 ns)',
    derivation: [
      'A modern core has a deep pipeline (~15–20 stages) full of instructions it started on a GUESS about which way a branch would go.',
      'Guess wrong and every stage after the branch is garbage: the pipeline flushes and refills — ~15 cycles of nothing.',
      'At ~0.3 ns/cycle that is ~5 ns per miss — trivial once, brutal across a hot loop that mispredicts half its branches.',
    ],
    boundingPhysics: 'Pipeline depth: the deeper the pipeline (the price of a high clock), the more work a single wrong guess throws away.',
    toyId: 'branch-predictor',
    confusions: 'Real predictors are ~95%+ accurate on typical code — the toy shows the PENALTY, not the average. Data-dependent (unpredictable) branches are the ones that hurt.',
  },
  {
    id: 'compress-1kb',
    value: 2_000,
    unit: 'ns',
    derivation: [
      'Fast compressors (snappy, lz4) run ~500 MB/s per core.',
      '1 KB ÷ 500 MB/s ≈ 2 µs ≈ 6,000 cycles for a 2–4× size cut.',
      'Sending that KB cross-region costs 70,000,000 ns — paying 2,000 ns to halve the bytes is a ~1000:1 win.',
    ],
    boundingPhysics: 'Pure CPU arithmetic — which is exactly the point: compute is the cheap resource.',
    toyId: null,
    confusions: 'Heavy compressors (gzip -9, brotli) are 10–50× slower; the interview instinct is fast-compression-by-default, not max ratio.',
  },
  {
    id: 'nvme-read',
    value: 80_000,
    unit: 'ns',
    derivation: [
      'Flash stores bits as electrons trapped in a floating gate; TLC packs 3 bits per cell as 8 distinguishable charge levels.',
      'Reading = applying stepped voltages and sensing which cells conduct ≈ 50–100 µs of careful analog work.',
      'Call it 80 µs per random read — 800× slower than DRAM, but it survives power-off.',
    ],
    boundingPhysics: 'Charge-sensing precision: more bits per cell = finer voltage steps = slower, less durable reads.',
    toyId: 'light',
    confusions: 'Latency is physics but throughput is parallelism — one drive still does ~500k–1M IOPS because thousands of reads run at once.',
    simplifies: 'Page (~16 KB) granularity, erase blocks, and the translation layer (write amplification) are hidden here.',
  },
  {
    id: 'same-dc-rtt',
    value: 500_000,
    unit: 'ns',
    derivation: [
      'Propagation across a 100 m building is ~0.5 µs — essentially nothing.',
      'The other ~499.5 µs is software: serialization, 2–3 switch hops, and the kernel network stack + scheduling on both ends.',
      '≈ 0.5 ms per in-DC round trip; a request fanning through 6 internal services pays ~3 ms before doing any work.',
    ],
    boundingPhysics: 'Inside a datacenter the floor is software, not light — which is why kernel-bypass and RDMA exist.',
    toyId: null,
    confusions: 'Do not confuse with cross-region RTT (~140× worse) — "a network call" is not one number.',
  },
  {
    id: 'hdd-seek',
    value: 8_000_000,
    unit: 'ns',
    derivation: [
      'A 7200 RPM platter spins 120 times/sec → one revolution = 8.33 ms → you wait half a spin (~4.2 ms) on average for your sector.',
      'Plus the head physically swings to the right track: ~4 ms of moving metal.',
      '≈ 8 ms per random read → ~120 random reads/second, forever.',
    ],
    boundingPhysics: 'Rotation speed — bounded by the platter tearing itself apart. This number cannot be engineered away.',
    toyId: 'disk',
    confusions: 'Sequential is the loophole: once positioned, data streams at ~200 MB/s — a 1000:1 asymmetry that designed the entire data stack.',
  },
  {
    id: 'cross-region-rtt',
    value: 70_000_000,
    unit: 'ns',
    derivation: [
      'Light in fiber (refractive index ~1.47) travels ~200,000 km/s.',
      'NY↔SF ≈ 4,700 km of non-straight fiber → ~24 ms one way → ~48 ms round trip as an absolute floor.',
      'Routing and queuing bring reality to ~60–80 ms; call it 70 ms.',
    ],
    boundingPhysics: 'The speed of light in glass. No engineering fixes this; CAP is geography.',
    toyId: 'light',
    confusions: 'Consensus needs MULTIPLE round trips — global strong writes cost ~150 ms, not 70.',
  },

  /* ---------- rates & capacities ---------- */
  {
    id: 'req-per-day-rule',
    value: 12,
    unit: 'req/s per 1M/day',
    derivation: [
      'One day is 86,400 seconds.',
      '1,000,000 ÷ 86,400 ≈ 11.6.',
      'Shortcut worth memorizing: 1M/day ≈ 12/s average.',
    ],
    boundingPhysics: 'Arithmetic — the length of a day.',
    toyId: null,
    confusions: 'That is the AVERAGE; consumer traffic peaks at 2–5× average, so quote both numbers.',
  },
  {
    id: 'peak-multiplier',
    value: 3,
    unit: '× average (2–5 range)',
    derivation: [
      'Human traffic is diurnal: most of a region is active in the same few evening hours.',
      'Squeezing ~50% of daily traffic into ~4 of 24 hours ≈ 3× the flat average.',
      'Design for the peak, pay for the average — that tension is what queues and autoscaling are for.',
    ],
    boundingPhysics: 'Human sleep schedules, not silicon.',
    toyId: null,
    confusions: 'Machine (IoT) traffic is flat 24/7 — no peak hours, but brutal synchronized bursts instead.',
  },
  {
    id: 'hdd-iops',
    value: 120,
    unit: 'IOPS',
    derivation: [
      'Every random read costs ~8 ms of rotation + seek (see hdd-seek).',
      '1000 ms ÷ 8 ms ≈ 120 operations per second.',
      'B-trees, LSM-trees, WALs, and Kafka all exist to dodge this number.',
    ],
    boundingPhysics: 'Rotation physics — same bound as hdd-seek, expressed as a rate.',
    toyId: 'disk',
    confusions: 'An SSD does ~500k–1M IOPS; if a design assumes spinning disks, say so out loud.',
  },
  {
    id: 'nvme-iops',
    value: 750_000,
    unit: 'IOPS (500k–1M)',
    derivation: [
      'One flash read takes ~80 µs (see nvme-read), so one channel does only ~12k/s.',
      'But a drive has many dies and deep queues — thousands of reads in flight at once.',
      'Parallelism × per-read physics ≈ 500k–1M random reads/s per drive.',
    ],
    boundingPhysics: 'Latency is charge-sensing physics; throughput is how many sensors run in parallel.',
    toyId: null,
    confusions: 'One thread doing sequential dependent reads gets ~12k/s, not a million — IOPS numbers assume queue depth.',
  },
  {
    id: 'redis-ops',
    value: 100_000,
    unit: 'ops/s per node',
    derivation: [
      'A GET is a hash lookup in RAM: ~1 µs of actual work → in theory 1M/s per core.',
      'Network syscalls eat most of it; pipelining wins some back.',
      '~100k ops/s per node is the honest planning number.',
    ],
    boundingPhysics: 'Kernel networking overhead per request, not the lookup itself.',
    toyId: null,
    confusions: 'It is 10× a database because it skips disk and the query engine — not because RAM is magic.',
    simplifies: 'Ignores connection limits, big values, hot-key skew, and cold-start warmup.',
  },
  {
    id: 'kafka-msgs',
    value: 1_000_000,
    unit: 'msgs/s per broker',
    derivation: [
      'Kafka only appends sequentially — recall the disk toy: sequential I/O is ~1000× cheaper than random.',
      '1 KB × 1M/s = 1 GB/s, within NVMe sequential bandwidth.',
      '~1M small msgs/s per broker: fast because it refuses to do random I/O, not because of magic.',
    ],
    boundingPhysics: 'Sequential disk bandwidth plus zero-copy networking.',
    toyId: 'disk',
    confusions: 'Consumers that fall behind and read old data turn the workload random again — and the number collapses.',
  },
  {
    id: 'pg-writes',
    value: 8_000,
    unit: 'TPS (5–10k)',
    derivation: [
      'Every commit must fsync the write-ahead log — bounded by sequential flush latency, not CPU.',
      'Group commit batches many transactions per flush, buying thousands, not millions.',
      '5–10k durable TPS is the classic single-primary ceiling; past it you shard or buffer through a queue.',
    ],
    boundingPhysics: 'fsync durability: the write must physically reach non-volatile media before "saved".',
    toyId: 'dram',
    confusions: 'Read throughput is 3–5× higher because cached reads never touch the truth on disk.',
    simplifies: 'Real ceilings vary with row size, indexes, and replication mode; this is the planning number.',
  },
  {
    id: 'pg-reads',
    value: 30_000,
    unit: 'QPS (20–50k)',
    derivation: [
      'A cached point read is a few B-tree hops in RAM + protocol overhead ≈ 0.1–0.5 ms.',
      'Across cores with connection overhead: tens of thousands per second.',
      '20–50k cached QPS; uncached (touching disk) divides by ~10.',
    ],
    boundingPhysics: 'Memory access + per-connection software overhead.',
    toyId: null,
    confusions: '"Working set fits in RAM" is doing all the work in this number — check it before quoting it.',
  },
  {
    id: 'app-server-rps',
    value: 10_000,
    unit: 'req/s per box',
    derivation: [
      'A simple request costs ~1–2 ms of CPU (parse, validate, serialize).',
      'One core: 1000 ms ÷ 1.5 ms ≈ 700 req/s.',
      '16 cores × 700 ≈ 11k — call it 10k req/s per box.',
    ],
    boundingPhysics: 'CPU cycles per request; cores per box (heat-bounded, see cpu-cycle).',
    toyId: 'queue',
    confusions: '"Simple" is load-bearing: one downstream call or JSON blob 10× bigger changes the answer.',
    simplifies: 'The simulator treats app servers as perfectly interchangeable and stateless.',
  },
  {
    id: 'queue-knee',
    value: 0.8,
    unit: 'utilization',
    derivation: [
      'Random arrivals clump; near full utilization there is no slack to absorb a clump.',
      'Waiting time grows like 1/(1−u) — gentle at 0.5, vertical past ~0.8.',
      'Every cheat-sheet scale trigger (CPU > 70%, memory > 80%) is this same knee on this same curve.',
    ],
    boundingPhysics: 'Queueing theory (M/M/1): variance + finite capacity, true of any server anywhere.',
    toyId: 'queue',
    confusions: 'Throughput barely changes as you cross the knee — it is WAITING that explodes, which is why the failure surprises people.',
  },
  {
    id: 'partition-write-cap',
    value: 1_000,
    unit: 'writes/s per partition',
    derivation: [
      'A partitioned store (DynamoDB, Cassandra) spreads KEYS across nodes; each partition lives on one node with finite I/O.',
      'DynamoDB documents the ceiling: ~1,000 write units per second per partition, no matter how big the table is.',
      'Total cluster capacity = partitions × 1k — but only if your keys actually spread. One hot key gets exactly one partition.',
    ],
    boundingPhysics: 'Single-node write throughput: one partition is ultimately one machine fsyncing.',
    toyId: 'hotpartition',
    confusions: 'Provisioning more total capacity does not fix a hot key — per-partition ceilings are per-key-range, not per-table.',
  },
  {
    id: 'bdp',
    value: 8_750_000,
    unit: 'bytes in flight (1 Gbps × 70 ms)',
    derivation: [
      'A sender may only have one congestion window of unacknowledged data in flight; more must wait for ACKs a full RTT away.',
      'Max throughput of one stream = window ÷ RTT. To fill the link, window must equal bandwidth × RTT.',
      '1 Gbps × 70 ms = 125 MB/s × 0.07 s ≈ 8.75 MB of in-flight data — far above default windows, which is why one cross-country TCP stream rarely fills a fat pipe.',
    ],
    boundingPhysics: 'The ACK must physically travel back: window sizing is the speed of light showing up in TCP.',
    toyId: 'pipe',
    confusions: 'Bandwidth is not throughput: a 1 Gbps link with a small window and long RTT delivers a tiny fraction of 1 Gbps per stream.',
  },
  {
    id: 'server-cost',
    value: 150,
    unit: '$/mo per 16-core box',
    derivation: [
      'Cloud on-demand pricing lands near $0.04–0.06 per vCPU-hour for general-purpose instances.',
      '16 vCPUs × ~730 h × $0.05 ≈ $580 list — but reserved/spot and right-sizing cut 60–75%.',
      '~$150/mo is the honest planning number for a committed 16-core app box.',
    ],
    boundingPhysics: 'Silicon amortization + datacenter power; compute is the commodity.',
    toyId: null,
    confusions: 'Engineers cost ~100× more per month than a server — optimize people-time before shaving instances.',
  },
  {
    id: 'storage-cost',
    value: 0.02,
    unit: '$/GB/mo (object storage)',
    derivation: [
      'S3-class storage lists at ~$0.023/GB/mo, cheaper in colder tiers.',
      'A terabyte is ~$20/mo; a petabyte ~$20k/mo.',
      'Storage is rarely the budget item that kills you — egress and IOPS are.',
    ],
    boundingPhysics: 'Disk platter density; object stores sit right above raw disk economics.',
    toyId: null,
    confusions: 'Block storage (EBS) is ~4× this, and replicated databases store every byte 3+ times.',
  },
  {
    id: 'egress-cost',
    value: 0.09,
    unit: '$/GB to the internet',
    derivation: [
      'Cloud egress lists at ~$0.05–0.09/GB — orders of magnitude above what the bytes cost the provider.',
      'Storing 1 GB for a month ($0.02) is cheaper than sending it out once ($0.09).',
      'Serving 100 TB/mo of traffic ≈ $9,000 in egress alone — the quiet architecture tax.',
    ],
    boundingPhysics: 'Not physics — pricing strategy. Which is exactly why CDNs and colocation exist.',
    toyId: null,
    confusions: 'Ingress is free; the meter only runs on the way OUT. Data gravity is a billing phenomenon.',
  },
  {
    id: 'page-requests',
    value: 70,
    unit: 'requests per page load',
    derivation: [
      'A modern page pulls HTML, then CSS/JS bundles, fonts, images, and a burst of API/analytics calls.',
      'HTTP Archive medians hover around 70 requests and ~2 MB per page.',
      'So "10k page views/s" is really ~700k requests/s somewhere — mostly absorbable at the CDN edge.',
    ],
    boundingPhysics: 'Nothing physical — accumulated front-end habit. But capacity math must use it.',
    toyId: null,
    confusions: 'API traffic ≠ page traffic: one SPA page load can be 1 backend call or 40 depending on design.',
  },

  {
    id: 'post-journey-total',
    value: 200_000_000,
    unit: 'ns',
    derivation: [
      'Your tap crosses the country to the app: ~35 ms one way (half a cross-region round trip).',
      'Queueing, app compute, a cache miss, and the local commit add single-digit milliseconds — noise next to the network.',
      'Cross-region consensus makes it durable in three cities: ~2 round trips ≈ 150 ms. 35 + 150 + change ≈ 200 ms.',
    ],
    boundingPhysics:
      'Two speed-of-light legs: reaching the server, then agreement among distant replicas. Engineering shaves the milliseconds in the middle; the geography stays.',
    toyId: 'consensus',
    confusions:
      "Assumes a strongly-consistent cross-region write. With async replication the ack returns in ~70–80 ms — durable in one city, the other copies arriving moments later.",
  },

  /* ---------- the transport floor (spec 066, Say-it networking deck) ---------- */
  {
    id: 'udp-vs-tcp-header',
    value: 8,
    unit: 'bytes (UDP header)',
    derivation: [
      'UDP carries four 2-byte fields — source port, destination port, length, checksum — and nothing else: 8 bytes.',
      'TCP needs sequence + ack numbers, flags, a receive window, and options: 20 bytes minimum, up to 60.',
      "The bigger tax isn't the header: TCP's 3-way handshake spends a full round trip before the first data byte; UDP just sends.",
    ],
    boundingPhysics: 'Protocol design, not physics — but every byte rides every packet, and the handshake rides every new connection.',
    toyId: null,
    confusions:
      'The header gap is minor next to the behavioral gap: retransmission and ordering are where TCP latency actually comes from, not the 12 extra bytes.',
  },
  {
    id: 'retransmit-rtt',
    value: 1,
    unit: 'round trip minimum per retransmit',
    derivation: [
      'A lost TCP packet is detected by duplicate ACKs or a timeout — the sender must first learn about the loss, and that news travels a round trip.',
      'Recovery therefore costs ≥1 RTT: ~1 ms in-city, ~70 ms cross-country, ~150 ms cross-ocean.',
      'Until the retransmit lands, ordering holds every byte behind it — one lost packet is a visible freeze, then a fast-forward.',
    ],
    boundingPhysics: 'Speed of light in fiber (~200,000 km/s) sets the RTT floor; no protocol tuning beats geography.',
    toyId: 'light',
    confusions: 'The 1-RTT floor is the best case — a retransmission timeout on a quiet connection can cost several RTTs.',
  },
  {
    id: 'fiber-rtt-floor',
    value: 56,
    unit: 'ms round trip, NY↔London floor',
    derivation: [
      'Light in fiber travels at ~200,000 km/s — glass slows it to about two-thirds of its vacuum speed.',
      'New York to London is ~5,600 km, so one way costs 5,600 ÷ 200,000 ≈ 28 ms; there and back is ≥56 ms.',
      'That is the floor before a single byte is processed — every handshake, retransmit, and consensus round is priced in multiples of it.',
    ],
    boundingPhysics: 'Speed of light in glass; no protocol, codec, or amount of bandwidth shortens a round trip.',
    toyId: 'light',
    confusions:
      'Real routes are worse than the great-circle floor — cables detour and routers add queueing, so NY↔London measures ~70–80 ms in practice. And a fatter pipe does not help: bandwidth moves more bytes per trip, never the trip itself.',
  },
  {
    id: 'middlebox-idle-timeout',
    value: 60,
    unit: 's (typical idle timeout)',
    derivation: [
      'Proxies, load balancers, and NATs hold per-connection state, and reap idle connections to protect their own memory.',
      'Defaults cluster at 30–90 s — AWS ALB ships with 60 s.',
      'Any long-lived stream (SSE, WebSocket) must expect death near the minute mark: heartbeats delay it, reconnect-and-replay survives it.',
    ],
    boundingPhysics: 'Middlebox memory: every tracked connection is state, and idle reaping is how the box stays alive.',
    toyId: null,
    confusions: 'The clock measures idle time, not connection age — steady traffic (or a heartbeat) resets it.',
  },
  {
    id: 'protobuf-vs-json-size',
    value: 15,
    unit: 'bytes (protobuf) vs 40 (JSON)',
    derivation: [
      'The same { "id": "123", "name": "John Doe" } in JSON repeats its schema on every message — braces, quotes, field names: ~40 bytes.',
      'Protobuf compiles the schema out-of-band; the wire carries 1-byte field tags, varint lengths, and raw values: ~15 bytes.',
      '~2.7× smaller and far cheaper to parse (no string scanning) — the case for gRPC on high-rate internal calls.',
    ],
    boundingPhysics: 'Serialization is CPU plus bytes-on-wire; a binary format with an out-of-band schema minimizes both.',
    toyId: null,
    confusions: "The win assumes both ends share the compiled schema — exactly what public and browser clients can't be counted on for.",
  },

  /* ---------- capacity ceilings & scale triggers (spec 071, bundle N1) ---------- */
  {
    id: 'cache-memory-ceiling',
    value: 1,
    unit: 'TB of RAM per cache node',
    derivation: [
      'A cache is a hash table in one machine’s RAM, so its capacity ceiling is simply the largest memory you can rent on one box.',
      'Memory-optimized cloud instances ship 1–4 TB of DRAM; after per-key overhead (~50–100 bytes of pointers and metadata per entry) call ~1 TB the honest usable planning number.',
      'Check what you are actually caching: 100M user profiles × 1 KB = 100 GB — one tenth of one node, so the whole dataset fits in RAM with room to spare.',
    ],
    boundingPhysics: 'DIMM slots per socket × the largest module that ships — a packaging limit, not a physics one, which is why it moves upward every few years.',
    toyId: null,
    confusions: 'Most "we need a distributed cache" arguments are about availability and blast radius, not capacity — a single node already holds datasets far bigger than people assume.',
    simplifies: 'Ignores replication copies, fragmentation from mixed value sizes, and the fact that eviction starts biting well before the last byte.',
  },
  {
    id: 'db-storage-ceiling',
    value: 100,
    unit: 'TB on one database node (tens of TB is routine)',
    derivation: [
      'A single database node’s storage limit is how much disk you can physically attach to one server, not anything the database imposes.',
      'Storage-optimized instances attach 8–24 NVMe drives at 4–8 TB each ⇒ 30–100 TB of raw local disk per node.',
      'A 100 GB dataset is 0.1% of that ceiling — so "we ran out of disk" is almost never the real reason a team shards.',
    ],
    boundingPhysics: 'Drive bays and PCIe lanes per chassis; beyond that you are buying a second machine, which is what sharding is.',
    toyId: null,
    confusions: 'Storage capacity and write throughput are different ceilings — you usually hit pg-writes (5–10k TPS) long before you hit 100 TB, and that is what forces sharding.',
    simplifies: 'Backup windows, restore time, and vacuum/compaction overhead all get painful well before the disk is full.',
  },
  {
    id: 'db-connection-ceiling',
    value: 500,
    unit: 'concurrent connections per database',
    derivation: [
      'PostgreSQL forks a full OS process per connection, each with its own private memory (work_mem, catalog caches, buffers) — roughly 5–10 MB even while idle.',
      '500 × 10 MB = 5 GB of RAM spent before a single query runs, and the kernel is now scheduling 500 processes across ~16 cores.',
      '200–500 is the practical ceiling; past it you add a pooler (pgbouncer) in front, not a bigger box — more connections buys contention, not throughput.',
    ],
    boundingPhysics: 'Per-connection process memory plus scheduler context-switching cost — the machine has cores, not connections, doing the work.',
    toyId: 'connpool',
    confusions: 'Connection count is not concurrency: 500 connections on 16 cores means 484 of them are waiting. The pool in front of the database is a queue, and it is invisible on database dashboards.',
  },
  {
    id: 'app-connection-ceiling',
    value: 50_000,
    unit: 'concurrent open connections per app server',
    derivation: [
      'On an event-loop server an idle connection is not a thread — it is a socket, two kernel buffers, and one entry in the poller.',
      '~10 KB of kernel buffers + ~40 KB of application state ⇒ 50,000 connections ≈ 2.5 GB, comfortably inside a 16–64 GB box.',
      'So the ceiling is memory and file descriptors (10k–100k per node), not CPU — which is why one server can hold a stadium’s worth of idle WebSockets.',
    ],
    boundingPhysics: 'Per-socket kernel memory and the file-descriptor limit; with an O(1) poller (epoll/kqueue) idle connections cost storage, not cycles.',
    toyId: null,
    confusions: 'Thread-per-connection collapses two orders of magnitude earlier (~1,000), because a thread costs a whole 1–8 MB stack. Holding a connection is cheap; doing work on it is not.',
    simplifies: 'Assumes mostly-idle connections. 50k connections each sending a message per second is 50k req/s — five times one box’s app-server-rps.',
  },
  {
    id: 'broker-storage-ceiling',
    value: 10,
    unit: 'TB retained per broker',
    derivation: [
      'A Kafka broker is an append-only log on local disks: writes are sequential, reads are sequential, so retention capacity is just attached disk.',
      '12 drives × 4 TB ≈ 48 TB raw ÷ replication factor 3 ≈ 16 TB of unique data — call it ~10 TB as a planning number.',
      'At 100 MB/s of ingest, 10 TB is 10e12 ÷ 100e6 = 100,000 s ≈ 28 hours of retention: how long you can replay is a disk budget, not a config whim.',
    ],
    boundingPhysics: 'Sequential disk is cheap — even spinning platters stream at ~200 MB/s (see hdd-seek), so a log broker is bounded by capacity, not IOPS.',
    toyId: null,
    confusions: 'Retention is not a backup. "7-day retention" means a consumer that is down for 8 days has permanently lost those messages, not that they are archived somewhere.',
  },
  {
    id: 'partition-count-ceiling',
    value: 200_000,
    unit: 'partitions per cluster (~4k per broker)',
    derivation: [
      'Every partition is its own set of files plus a leader-election entry in cluster metadata, and each one costs open file handles, a replication fetch loop, and periodic heartbeats.',
      '~4,000 partitions per broker × ~50 brokers ≈ 200,000 per cluster before metadata propagation and leader elections become the bottleneck.',
      'Partitions are the unit of parallelism AND of metadata cost, so "just add partitions" runs out — and failover time scales with the count, because every partition on a dead broker needs a new leader.',
    ],
    boundingPhysics: 'Control-plane bookkeeping: one metadata record and one replication stream per partition, all of which must be gossiped and re-elected on failure.',
    toyId: null,
    confusions: 'You cannot have more consumers than partitions in a group — extra consumers sit idle. Partition count is the concurrency ceiling of the consuming side too.',
  },
  {
    id: 'container-start-time',
    value: 5,
    unit: 'seconds to add a container',
    derivation: [
      'Scaling out is not instant: the scheduler must place the pod, mount or pull the image, start the runtime, warm the JIT/connection pools, and then pass a health check.',
      '~1 s scheduling + ~1–3 s runtime and warmup + a 1–5 s health-check interval ⇒ ~5–10 s when the image is already cached on the node; minutes when it is not.',
      'So autoscaling cannot answer a spike that arrives in under a minute — by the time capacity exists, the traffic has already queued or been dropped.',
    ],
    boundingPhysics: 'Image-pull bandwidth and health-check interval, not CPU — the machine is mostly waiting.',
    toyId: null,
    confusions: 'Autoscaling is a cost-control mechanism, not a burst-absorption mechanism. Bursts are absorbed by headroom you already paid for, or by a queue.',
  },
  {
    id: 'dc-bandwidth',
    value: 10,
    unit: 'Gbps per server NIC (25–100 in modern DCs)',
    derivation: [
      'Inside a data center, bandwidth is a purchased NIC and switch port — no physics involved, unlike latency.',
      '10 Gbps = 1.25 GB/s, so moving 1 TB between two machines takes 1e12 ÷ 1.25e9 ≈ 800 s ≈ 13 minutes at full line rate.',
      'Per request that is irrelevant; per bulk job it is the whole story — and cross-region the same bytes cost money (egress-cost), turning bandwidth from a time problem into a bill.',
    ],
    boundingPhysics: 'Purchased capacity: NIC, switch port, and oversubscription ratio of the top-of-rack uplink.',
    toyId: 'pipe',
    confusions: 'Line rate is not per-stream rate — one TCP connection is capped by window ÷ RTT (see bdp), so saturating a 10 Gbps link usually needs many parallel streams.',
  },
  {
    id: 'az-rtt',
    value: 1_000_000,
    unit: 'ns',
    derivation: [
      'Availability zones are separate buildings, typically 1–100 km apart, connected by dedicated fiber — so a cross-AZ hop adds real propagation on top of the same-DC software floor.',
      '~50 km each way ÷ 200,000 km/s ≈ 0.25 ms of propagation, plus the ~0.5 ms software floor (same-dc-rtt) ≈ 1 ms round trip.',
      'That completes the three-tier ladder: same-zone ~0.5 ms, cross-AZ ~1 ms, cross-region ~70 ms — synchronous replication across AZs is nearly free, across regions it is not.',
    ],
    boundingPhysics: 'A few tens of km of glass — enough to be measurable, nowhere near enough to matter the way cross-region distance does.',
    toyId: 'consensus',
    confusions: 'Multi-AZ is the default answer to "survive a data-center failure" precisely because the latency cost is ~0.5 ms. Multi-region is a different question with a 140× different price.',
  },
  {
    id: 'cpu-scale-trigger',
    value: 70,
    unit: '% CPU sustained → add capacity',
    derivation: [
      'Queueing theory, not headroom sentiment: waiting time grows like 1/(1−u), so the last slice of utilization is where latency lives.',
      '1 ÷ (1 − 0.70) = 3.3× the service time spent waiting; 1 ÷ (1 − 0.90) = 10×. Those last 20 points of "spare" CPU triple your latency.',
      'So scale at ~70% sustained, not at 95% — you are buying distance from the knee (queue-knee), not buying CPU.',
    ],
    boundingPhysics: 'The M/M/1 knee: random arrivals clump, and a server with no slack has nowhere to put a clump.',
    toyId: 'queue',
    confusions: 'Throughput at 95% CPU looks fine on a dashboard — it is the p99 that has already left. Averages hide the knee completely.',
  },
  {
    id: 'shard-storage-trigger',
    value: 5,
    unit: 'TB of hot data per node → start sharding',
    derivation: [
      'You shard when one node can no longer hold the working set or absorb the write rate — not when the row count looks impressively large.',
      'Do the arithmetic first: 100M users × 1 KB/row = 100 GB; 1M orders/day × 1 KB × 365 days = 365 GB/year. Both are one to two orders of magnitude under one node’s 10–100 TB ceiling (db-storage-ceiling).',
      'The honest trigger is a few TB of HOT data (data that must stay in RAM or on fast local disk) or sustained writes past write-scale-trigger — below that, sharding buys you cross-shard joins, distributed transactions, and a rebalancing project in exchange for nothing.',
    ],
    boundingPhysics: 'RAM per node versus working-set size — the point where the cache-hit rate falls off a cliff and every read becomes disk I/O.',
    toyId: null,
    confusions: 'Premature sharding is the classic over-engineering tell. "It won’t scale" needs a number attached: total bytes, writes/s, or working-set size — otherwise it is a vibe.',
  },
  {
    id: 'read-scale-threshold',
    value: 10_000,
    unit: 'reads/s → add replicas or a cache',
    derivation: [
      'A single primary serves 20–50k cached queries/s (pg-reads), but it shares that capacity with writes, vacuum, and replication — and the knee arrives at ~80% of it (queue-knee).',
      '0.8 × 30,000 ≈ 24,000, minus write and maintenance headroom ⇒ plan to add read capacity around ~10,000 sustained reads/s.',
      'Which tool depends on the shape: replicas if reads are DIVERSE (they scale linearly, one machine each, at the cost of replication lag), a cache if reads are SKEWED (a small hot set absorbs most of the traffic).',
    ],
    boundingPhysics: 'One primary’s read ceiling met by the queueing knee — the trigger is the knee, not the ceiling.',
    toyId: null,
    confusions: 'Replicas do not help write throughput at all — every write still lands on the primary and then costs the replicas the same work. They buy read capacity and failover, nothing else.',
  },
  {
    id: 'write-scale-trigger',
    value: 5_000,
    unit: 'writes/s → shard or buffer',
    derivation: [
      'Four things actually cap a primary’s writes: WAL fsync latency, index maintenance (one extra write per index), lock contention on hot rows, and replication fan-out — none of which a queue in front removes.',
      'So convert the requirement before designing for it: 1,000 writes/s × 86,400 s = 86,400,000 writes/day — comfortably under one primary’s 5,000–10,000 TPS ceiling (pg-writes), with 5–10× headroom.',
      'Below ~5,000 writes/s, try batching commits, dropping an unused index, faster disks, and a wider connection pool BEFORE adding a queue or sharding.',
    ],
    boundingPhysics: 'fsync durability against a single log device — the same bound as pg-writes, expressed as a decision threshold.',
    toyId: null,
    confusions: 'A queue does not raise write throughput — it changes WHEN the writes land and who waits. If arrivals exceed the database’s sustained rate, the queue grows forever (see backpressure).',
  },

  /* ---------- storage & index mechanics (spec 071, bundle N2) ---------- */
  {
    id: 'disk-page-size',
    value: 8,
    unit: 'KB per database page',
    derivation: [
      'A database never reads a row — it reads the PAGE the row sits on. The page is the unit of I/O, of buffer-pool caching, and often of locking.',
      'PostgreSQL uses 8 KB, MySQL/InnoDB 16 KB; both are multiples of the 4 KB OS page (page-size) so one page write maps onto whole device blocks with no read-modify-write.',
      'Fetching one 200-byte row therefore costs a full 8 KB transfer — 40× read amplification, which is exactly why row stores are bad at scanning one column, and why a B-tree node is sized to fill precisely one page.',
    ],
    boundingPhysics: 'The storage device has a minimum transfer unit; anything smaller costs the same as the whole block, so the engine may as well use it.',
    toyId: null,
    confusions: 'Three different "pages" live in one stack: 64 B cache line (CPU), 4 KB virtual-memory page (OS), 8–16 KB database page (engine). They nest; they are not the same number.',
  },
  {
    id: 'btree-lookup-depth',
    value: 4,
    unit: 'page reads per lookup',
    derivation: [
      'A B-tree node is exactly one page (disk-page-size, 8 KB). With ~16-byte keys plus 8-byte child pointers, one node holds roughly 8192 ÷ 24 ≈ 340 children — fan-out in the hundreds, not two.',
      'Depth is a logarithm in that fan-out: 340 × 340 = 115,600 rows at depth 2, × 340 again ≈ 39,000,000 at depth 3, × 340 again ≈ 13 BILLION at depth 4. A 100-million-row table therefore sits at depth ~4.',
      'So a point lookup in a 100M-row table is ~4 page reads — and the top two or three levels are almost always resident in the buffer cache, making it ~1 actual disk read.',
    ],
    boundingPhysics: 'Logarithms with a huge base: fan-out is set by how many keys fit in one page, so depth grows almost imperceptibly with table size.',
    toyId: 'lsmbtree',
    confusions: 'This is why "the table got 10× bigger and lookups got slower" is usually false — depth barely moved. What actually slowed down is the buffer-cache hit rate, or maintenance (see pg-table-row-ceiling).',
  },
  {
    id: 'lsm-write-crossover',
    value: 10_000,
    unit: 'writes/s where an LSM beats a B-tree',
    derivation: [
      'A B-tree write must find and modify the page IN PLACE — a random write, plus the write-ahead-log append. An LSM appends to an in-memory memtable now and writes sequentially later.',
      'Random page writes cost roughly one I/O each, capping a B-tree near pg-writes (5–10k durable TPS). An LSM’s flush is one big sequential stream at 200 MB/s–1 GB/s, so the same disk absorbs 10–100× more writes.',
      'Above ~10,000 sustained writes/s the engine choice stops being taste: take the LSM and pay for it on reads, where you now check a memtable plus many SSTables instead of one tree.',
    ],
    boundingPhysics: 'The sequential-vs-random asymmetry of storage (~1000:1 on spinning disk, still ~10:1 on NVMe) — an LSM converts random writes into sequential ones.',
    toyId: 'lsmbtree',
    confusions: 'The LSM does not make writes free, it defers them: compaction re-reads and re-writes the same data several times later. You pay in background I/O and read amplification instead of at commit time.',
    simplifies: 'Bloom filters, sparse indexes, and compaction strategy (leveled vs size-tiered) move the read penalty a lot — the crossover is a band, not a line.',
  },
  {
    id: 'memtable-flush-size',
    value: 64,
    unit: 'MB per memtable before flush',
    derivation: [
      'An LSM buffers incoming writes in a sorted in-memory table and flushes it to an immutable on-disk SSTable when it fills — the threshold is a three-way trade between RAM, crash-recovery time, and read amplification.',
      'At 10,000 writes/s × 1 KB = 10 MB/s, a 64 MB memtable fills every ~6.4 seconds — roughly 560 SSTables per hour arriving for compaction to merge.',
      'Bigger memtables mean fewer, larger SSTables (less read amplification, less compaction churn) but more RAM held and a longer write-ahead-log replay after a crash; 64 MB is the common default landing spot.',
    ],
    boundingPhysics: 'RAM you are willing to lose to a buffer, against the WAL you must replay to get it back after a crash.',
    toyId: 'lsmbtree',
    confusions: 'The memtable is not the durability mechanism — the write-ahead log is. A write is safe the moment the WAL is fsynced, long before the memtable flushes.',
  },
  {
    id: 'quadtree-split-threshold',
    value: 100,
    unit: 'points per node before it splits into four',
    derivation: [
      'A quadtree subdivides a region into four quadrants whenever a node holds more than a fixed number of points — so dense areas grow deep and empty ocean stays a single node.',
      'With a threshold near 100, scanning a leaf is 100 distance computations (a few microseconds of pure arithmetic), while one more level of tree costs a pointer chase and possibly a page read. The threshold is set where scanning becomes cheaper than descending.',
      'Adaptive resolution is the whole point: a query over Manhattan and a query over the mid-Pacific both touch a handful of nodes — which is exactly what a uniform grid cannot do.',
    ],
    boundingPhysics: 'The scan-versus-descend crossover: a linear scan of a small array in cache beats a tree hop that may miss (see l1-hit vs dram-access).',
    toyId: null,
    confusions: 'Two separate one-dimensional B-tree indexes (one on latitude, one on longitude) cannot answer a proximity query efficiently — the planner picks one, then filters a stripe of the planet by hand.',
  },
  {
    id: 'index-table-threshold',
    value: 1_000,
    unit: 'rows below which an index is pointless',
    derivation: [
      'The planner compares two plans: a sequential scan (read every page in order, streaming) versus an index scan (walk the B-tree, then a RANDOM heap fetch per matching row).',
      '1,000 rows × 200 bytes ≈ 200 KB ≈ 25 pages of 8 KB, read as one sequential burst in well under a millisecond. The index route pays btree-lookup-depth page reads plus a random heap fetch for every row it returns.',
      'Sequential wins until the table is at least a few thousand rows AND the query selects a small fraction of them — below that the index is pure write amplification and wasted space, and the planner will correctly ignore it.',
    ],
    boundingPhysics: 'Sequential throughput versus random-access latency — the same asymmetry as hdd-seek, still material on SSD.',
    toyId: null,
    confusions: 'People add an index, see no improvement, and conclude the index is broken. The planner simply measured and chose the scan — which is the right call on a small or low-selectivity table.',
  },
  {
    id: 'pg-indexed-lookup-rate',
    value: 3_000,
    unit: 'indexed lookups/s per connection (~0.3 ms each)',
    derivation: [
      'An indexed lookup with the index cached and the heap page on disk is one NVMe read (~80 µs, see nvme-read) plus query-parse, plan, execute, and protocol overhead of ~0.2 ms.',
      '≈ 0.3 ms per lookup ⇒ a single connection issuing them back to back gets 1000 ÷ 0.3 ≈ 3,000/s; the connection pool multiplies that up to the server-wide band (pg-reads).',
      'The teaching is the latency, not the rate: an indexed lookup ALREADY costs a fraction of a millisecond, so putting a cache in front of it to save ~0.3 ms is not a latency argument.',
    ],
    boundingPhysics: 'One random storage read plus fixed per-query software cost — the software is now the bigger half.',
    toyId: null,
    confusions: 'Caches in front of an indexed database earn their keep by removing LOAD (see read-scale-threshold), not by removing latency. "The database is slow" usually means a missing index or a full scan, not storage physics.',
  },
  {
    id: 'pg-table-row-ceiling',
    value: 100_000_000,
    unit: 'rows in one table before partitioning pays',
    derivation: [
      'Lookups do not care about row count — a B-tree over 100M rows is still only ~4 levels deep (btree-lookup-depth). What scales linearly with size is MAINTENANCE: vacuum, index rebuilds, backups, and restores.',
      '100M rows × 1 KB = 100 GB of heap plus ~20 GB of index. A full vacuum or index rebuild now streams 120 GB — minutes of pure I/O at 1 GB/s, and hours of lock and bloat contention on a live system.',
      'So the ceiling is operational, not algorithmic: partition at ~100M rows because your maintenance window stopped fitting overnight, not because queries got slower.',
    ],
    boundingPhysics: 'Full-table operations are O(bytes) against a fixed disk bandwidth — the one part of a database that cannot be made logarithmic.',
    toyId: null,
    confusions: 'Partitioning is not sharding. Partitioning splits one table across files on ONE machine (smaller maintenance units); sharding splits data across machines and brings distributed transactions with it.',
  },
  {
    id: 'pg-join-ceiling',
    value: 8,
    unit: 'tables per join before the planner stops searching exhaustively',
    derivation: [
      'The planner does not just pick access methods, it picks a join ORDER — and n tables admit n! orderings, each of which must be costed.',
      '8! = 40,320 candidate orders is cheap to enumerate; 12! = 479,001,600 is not. So PostgreSQL caps exhaustive search at join_collapse_limit = 8 and switches to a genetic (approximate) search at geqo_threshold = 12.',
      'Past ~8 joined tables you are trusting a heuristic: plan quality becomes a coin flip that can change under you after a statistics refresh — which is the real reason teams denormalize, not raw join cost.',
    ],
    boundingPhysics: 'Combinatorial explosion — factorial growth in the plan space against a planning budget measured in milliseconds.',
    toyId: null,
    confusions: '"Joins are slow" is mostly folklore; a well-indexed 3-table join is fast. The risk at high join counts is PLAN INSTABILITY, which feels like random production slowness rather than steady slowness.',
  },
  {
    id: 'ddb-item-max',
    value: 400,
    unit: 'KB per item',
    derivation: [
      'DynamoDB caps a single item (its row) at 400 KB, because an item must fit inside one partition’s storage and replication unit and be returned whole in one response.',
      '400 KB ÷ 4 KB per read unit = 100 RCUs to read one maximal item strongly-consistently (ddb-rcu-bytes) — that is 3% of a partition’s entire 3,000 RCU/s budget spent on ONE read.',
      'The ceiling is a design nudge, not an arbitrary limit: put big payloads in blob storage and keep a pointer plus metadata in the item.',
    ],
    boundingPhysics: 'A single item is the unit of atomicity and replication, so it must fit comfortably in one node’s memory and one network response.',
    toyId: null,
    confusions: 'Hitting the item limit is usually a modeling smell (an unbounded list embedded in a row), not a size problem — the fix is a new item collection or a blob, not compression.',
  },
  {
    id: 'ddb-rcu-bytes',
    value: 4,
    unit: 'KB per read capacity unit',
    derivation: [
      'DynamoDB bills reads in fixed quanta rather than per query: one read capacity unit = one strongly-consistent read of up to 4 KB, or TWO eventually-consistent reads of up to 4 KB.',
      'So a 10 KB item costs ceil(10 ÷ 4) = 3 RCUs strongly consistent, and 1.5 eventually consistent. Reading 1,000 of them per second = 3,000 RCU/s — exactly one partition’s ceiling (ddb-partition-capacity).',
      'Item size is therefore a capacity decision, not just a schema decision — and choosing eventual consistency is literally half price for the same bytes.',
    ],
    boundingPhysics: 'Billing quanta chosen to match the underlying page/transfer size — you pay for blocks moved, not rows returned.',
    toyId: null,
    confusions: 'A query that returns 1 item out of a 100-item partition still charges for every item it READ before filtering. Filter expressions cost full capacity; key conditions do not.',
  },
  {
    id: 'ddb-wcu-bytes',
    value: 1,
    unit: 'KB per write capacity unit',
    derivation: [
      'One write capacity unit covers a write of up to 1 KB — a quantum four times finer than the read unit (ddb-rcu-bytes).',
      'A 3 KB item costs 3 WCUs per write; at 1,000 WCU/s per partition (partition-write-cap) that partition now absorbs only ~333 of those writes per second.',
      'Wide items hurt writes 4× more than reads, and every secondary index the write touches repeats the charge (ddb-index-maxima) — so item width compounds across the whole write path.',
    ],
    boundingPhysics: 'Writes must be durably replicated to a quorum of replicas, so the billable quantum is smaller than the read quantum.',
    toyId: null,
    confusions: 'Updating one attribute costs the same as rewriting the whole item — capacity is charged on item size, not on the size of the delta.',
  },
  {
    id: 'ddb-partition-capacity',
    value: 3_000,
    unit: 'read units/s per partition (≈12 MB/s)',
    derivation: [
      'A partition is one physical storage unit with a fixed slice of throughput, no matter how much capacity the table as a whole has provisioned.',
      '3,000 RCU/s × 4 KB per unit = 12 MB/s of reads. The write side is 1,000 WCU/s × 1 KB = 1 MB/s (partition-write-cap) — a 12:1 read/write asymmetry baked into the quanta.',
      'So a hot partition key is capped at ~12 MB/s of reads however large the table gets — the ceiling is per key range, which is why it surfaces as a throttling incident rather than a bill.',
    ],
    boundingPhysics: 'One partition is ultimately one machine’s I/O and one replication group — provisioning is a billing construct, the node is not.',
    toyId: 'hotpartition',
    confusions: 'Adaptive capacity and burst credits hide small hot spots, which makes the ceiling feel soft — until a genuinely viral key hits it and throttles at a fraction of your provisioned table capacity.',
    simplifies: 'Real tables split hot partitions in the background; the split takes minutes, which is far too slow for a per-second spike.',
  },
  {
    id: 'ddb-index-maxima',
    value: 20,
    unit: 'global secondary indexes per table (5 local)',
    derivation: [
      'Each global secondary index is a full, separately-partitioned COPY of the table keyed differently, maintained asynchronously on every base-table write.',
      'A write fans out to every index whose keys it touches: with 20 GSIs, one logical write can become up to 21 writes billed and replicated — the classic one-extra-write-per-index amplification, priced explicitly.',
      'Local secondary indexes are capped far lower (5) and must be declared at table creation, because they share the base table’s partitions rather than getting their own.',
    ],
    boundingPhysics: 'Write amplification: every index is another sorted structure that must be kept consistent with the base data on every mutation.',
    toyId: null,
    confusions: 'GSIs are eventually consistent even when the base table read is strong — the index copy is updated asynchronously, so read-after-write against a GSI can miss.',
  },
  {
    id: 'ddb-txn-items',
    value: 100,
    unit: 'items per transaction',
    derivation: [
      'A DynamoDB transaction is a two-phase commit coordinated across every partition that holds an affected item, so its cost scales with the number of PARTICIPANTS, not the bytes.',
      '100 items may live on 100 different partitions: the coordinator runs prepare and commit rounds against up to 100 nodes, and the transaction is billed at 2× the normal capacity units for exactly that reason.',
      'The cap bounds any single transaction’s blast radius and lock duration — if a workflow needs more than 100 items to move together, it is a saga with compensations, not a transaction.',
    ],
    boundingPhysics: 'Two-phase commit holds locks across a network round trip per participant; the window during which everyone is blocked grows with the participant count.',
    toyId: null,
    confusions: 'Multi-item transactions in a partitioned store are not the same primitive as a single-node ACID transaction — they are more expensive, more limited, and can fail on contention rather than waiting.',
  },
  {
    id: 'cassandra-quorum',
    value: 2,
    unit: 'nodes (QUORUM at RF=3)',
    derivation: [
      'Cassandra tunes consistency per query: you choose how many replicas must answer a read (R) and how many must acknowledge a write (W), out of a replication factor N.',
      'With N = 3, QUORUM = floor(3 ÷ 2) + 1 = 2. Then W + R = 2 + 2 = 4 > 3 = N — and since any two-node write set and any two-node read set are both drawn from the same three nodes, they must SHARE at least one node.',
      'That shared node is the whole guarantee: it holds the latest write and is present in the read, so the read cannot miss it. Strong consistency here is pigeonhole arithmetic, not a feature flag.',
    ],
    boundingPhysics: 'The pigeonhole principle applied to replica sets — overlap, not coordination, is what makes the read see the write.',
    toyId: 'consensus',
    confusions: 'R=1/W=1 is fast and CAN return stale data; R=1/W=3 is strongly consistent for reads but unavailable if any replica is down. Do the W + R > N arithmetic and you know which one you actually deployed.',
  },
  {
    id: 'replication-factor',
    value: 3,
    unit: 'copies of every row',
    derivation: [
      'Copies exist so data survives losing machines: with N copies you tolerate N−1 losses without losing data.',
      'RF = 2 survives one failure but leaves no quorum — a majority of 2 is still 2, so a single node down blocks every quorum write. RF = 3 keeps a majority (2 of 3) alive through one failure, and lets you put one copy in each of three availability zones (az-rtt).',
      '3 is the industry default because it is the cheapest number that separates "survives a failure" from "keeps WORKING during a failure" — two different guarantees people routinely conflate.',
    ],
    boundingPhysics: 'Majority quorums need an odd count to break ties; 3 is the smallest odd number greater than 1.',
    toyId: 'consensus',
    confusions: 'Replication (availability) and partitioning (scale) are separate concerns — a single database instance WITH replicas is not a single point of failure, and adding shards does not make anything more durable.',
  },
]

export const numberById = (id: string): NumberEntry | undefined => NUMBERS.find((n) => n.id === id)
